### ISSUE TITLE
Check return values of rocksdb API functions

### ISSUE THREAD

**Issue by uwiger** [aeternity/mnesia_rocksdb#12]
See e.g. in [`do_insert()`](https://github.com/aeternity/mnesia_rocksdb/blob/master/src/mnesia_rocksdb.erl#L1173)

The code simply assumes that `rocksdb:put/3` will return `ok`, and neither checks nor (of course) reports any exceptions.

There is no elegant way of failing in this layer, since the operations occur after Mnesia's commit point, but at least reporting an error seems like a minimum requirement.

**Comment by tolbrino** [comment]
I believe this task can be closed once #15 is merged.
