### ISSUE TITLE
use_bloomfilter -> bloom_filter_policy

### ISSUE THREAD

**Issue by aramallo** [aeternity/mnesia_rocksdb#23]
Hi @uwiger,

(Not and issue but a comment).

I am migrating one of my projects from elevedb to rocksdb and while checking the rocksdb gitlab issues I noticed [an issue of yours](https://gitlab.com/barrel-db/erlang-rocksdb/-/issues/120) with an example. In the example code and still on this repo's master branch  [here](https://github.com/aeternity/mnesia_rocksdb/blob/66e5a516345a81a73bddac490f9900a5ed8a4d80/src/mnesia_rocksdb.erl#L1064) you are using `use_bloomfilter` as a db_option during open.

AFAIK, in rocksdb 1.7 there is no such option and instead you have to use `bloom_filter_policy` with an integer value. 

`use_bloomfilter` was an option in eleveldb but not sure it was ever an option in rocksdb. 
It is certainly not defined in the `db_options()` type and I couldn't find it on the NIF code.

So I thought I should let you know.

**Comment by uwiger** [comment]
Thanks. Yes, in some places - not least the tuning code - there are bound to be leveldb-specific options that won't work with rockdb.
