### ISSUE TITLE
Does not work on Erlang/OTP 25+

### ISSUE THREAD

**Issue by florius0** [aeternity/mnesia_rocksdb#28]
The library fails to work with modern erlang versions due to `hut` dependecy usage of `rebar2`

**Comment by uwiger** [comment]
Can you give a specific example of how it fails?

I tried running `make` and `make test` using OTP 25.0.3, and this went well.

**Comment by florius0** [comment]
I did it without `make`. Just added it to mix deps and tried `mix deps.get && mix deps.compile`

**Comment by uwiger** [comment]
Could you try the above PR branch (using hut-1.4.0)?

**Comment by uwiger** [comment]
Merged into master
