### ISSUE TITLE
Failure to compile with gcc13

### ISSUE THREAD

**Issue by mariari** [aeternity/mnesia_rocksdb#40]
I've tried building the project with `gcc 13.2.1`, and it fails to compile.

It seems to be an upstream issue with `erlang-rocksdb` the following changes allow the base repo to compile

https://gitlab.com/seanhinde/erlang-rocksdb/-/merge_requests/2

addresses the issue, it would be nice to bump the version this library depends on to the integration of the patch and `add-rollback`

However even with this topic [integrated](https://gitlab.com/mariari/erlang-rocksdb/-/tree/mariari/add-rollback-integration?ref_type=heads)

I have issues using symbols in the `.so` file.

However no such issues exist upstream if we include the [patch made by vans](https://gitlab.com/barrel-db/erlang-rocksdb/-/merge_requests/150),

Further, judging by the history of the dependency, the following [commit](https://gitlab.com/barrel-db/erlang-rocksdb/-/commit/16e6cdcc29110b35fbf8a0b94cb1c9ff390b7821), seems to include the same changes the locked dependnecy of this code does.

It would likely make sense to just bump the dependency to the [commit by vans](https://gitlab.com/barrel-db/erlang-rocksdb/-/merge_requests/150)

**Comment by ThomasArts** [comment]
We no longer use https://gitlab.com/seanhinde/erlang-rocksdb/
If problems persists with specific compilers, please fix needs to be re-done
