### ISSUE TITLE
Index is not rebuilt when recreating it

### ISSUE THREAD

**Issue by Juliusan** [aeternity/mnesia_rocksdb#43]
When deleting and recreating table's secondary index, index metadata is not completely deleted from the store. `mnesia_rocksdb:index_is_consistent` returns `true` even after the index data gets deleted. Therefore, after the same index is recreated, Mnesia does not catch that it must be rebuild, as the data is not available, although `mnesia_rocksdb:index_is_consistent` results in `true`.

I suggest completely dropping index metadata on index deletion. This will result in it being recreated on add.

**Comment by uwiger** [comment]
Thanks. Will investigate.

**Comment by ThomasArts** [comment]
Seems solved by PR #44
